import 'package:google_maps_flutter/google_maps_flutter.dart';
import 'package:mymap/models/ride_data.dart';

class SampleRideService {
  static List<Ride> getSampleRides() {
    return [
      Ride(
        id: "1",
        title: "Golden Gate Bridge Ride",
        startTime: DateTime.parse("2024-03-15 14:44:00.000"),
        desc:
            "Enjoy a scenic ride across the iconic Golden Gate Bridge with breathtaking views of San Francisco.",
        snippet: "Best bike ride ever",
        startPointDesc: "Just under the bridge",
        contact: "Jeff Miller",
        phone: "555 123-4567",
        dow: DayOfWeekType.monday,
        latlng: const LatLng(37.8199, -122.4783),
        verified: true,
        verifiedBy: "mQOrVKoRv7NxRuFXFLzJznBIiYl1",
        createdBy: "tDWKQAecW5Msw5yXPQK4h5n7MXR2",
        rideType: RideType.roadRide,
        rideDistance: 20,
      ),
      Ride(
        id: "2",
        title: "Central Park Loop",
        startTime: DateTime.parse("2024-03-15 14:44:00.000"),
        desc:
            "Take a leisurely ride through the heart of Manhattan in the beautiful Central Park.",
        snippet: "Best bike ride ever",
        startPointDesc: "Just under the bridge",
        contact: "Jeff Miller",
        phone: "555 123-4567",
        dow: DayOfWeekType.monday,
        latlng: const LatLng(40.785091, -73.968285),
        verified: false,
        verifiedBy: "",
        createdBy: "tDWKQAecW5Msw5yXPQK4h5n7MXR2",
        rideType: RideType.roadRide,
        rideDistance: 20,
      ),
      Ride(
        id: "3",
        title: "Lakefront Trail",
        startTime: DateTime.parse("2024-03-15 14:44:00.000"),
        desc:
            "Ride along the picturesque Lake Michigan and enjoy the stunning Chicago skyline.",
        snippet: "Best bike ride ever",
        startPointDesc: "Lakeshore drive near the pier.",
        contact: "Jeff Miller",
        phone: "555 123-4567",
        dow: DayOfWeekType.monday,
        latlng: const LatLng(41.8833, -87.6197),
        verified: false,
        verifiedBy: "",
        createdBy: "mQOrVKoRv7NxRuFXFLzJznBIiYl1",
        rideType: RideType.roadRide,
        rideDistance: 20,
      ),
      Ride(
        id: "4",
        title: "Boston Harborwalk",
        startTime: DateTime.parse("2024-03-15 14:44:00.000"),
        desc:
            "Cycle along the historic Boston Harbor and explore the city's waterfront.",
        snippet: "Best bike ride ever",
        startPointDesc: "Just under the bridge",
        contact: "Jeff Miller",
        phone: "555 123-4567",
        dow: DayOfWeekType.monday,
        latlng: const LatLng(42.3601, -71.0589),
        verified: true,
        verifiedBy: "mQOrVKoRv7NxRuFXFLzJznBIiYl1",
        createdBy: "tDWKQAecW5Msw5yXPQK4h5n7MXR2",
        rideType: RideType.roadRide,
      ),
      Ride(
        id: "5",
        title: "Los Angeles River Bike Path",
        startTime: DateTime.parse("2024-03-15 14:44:00.000"),
        desc:
            "Follow the Los Angeles River through parks, neighborhoods, and urban landscapes.",
        snippet: "Best bike ride ever",
        startPointDesc: "Just under the bridge",
        contact: "Jeff Miller",
        phone: "555 123-4567",
        dow: DayOfWeekType.monday,
        latlng: const LatLng(34.0522, -118.2437),
        verified: true,
        verifiedBy: "mQOrVKoRv7NxRuFXFLzJznBIiYl1",
        createdBy: "tDWKQAecW5Msw5yXPQK4h5n7MXR2",
        rideType: RideType.roadRide,
        rideDistance: 20,
      ),
      Ride(
        id: "6",
        title: "Portland Eastbank Esplanade",
        startTime: DateTime.parse("2024-03-15 14:44:00.000"),
        desc:
            "Enjoy a scenic ride along the Willamette River with views of downtown Portland.",
        snippet: "Best bike ride ever",
        startPointDesc: "Just under the bridge",
        contact: "Jeff Miller",
        phone: "555 123-4567",
        dow: DayOfWeekType.monday,
        latlng: const LatLng(45.5175, -122.6651),
        verified: true,
        verifiedBy: "mQOrVKoRv7NxRuFXFLzJznBIiYl1",
        createdBy: "tDWKQAecW5Msw5yXPQK4h5n7MXR2",
        rideType: RideType.roadRide,
        rideDistance: 20,
      ),
      Ride(
        id: "7",
        title: "Minneapolis Chain of Lakes",
        startTime: DateTime.parse("2024-03-15 14:44:00.000"),
        desc:
            "Explore the interconnected lakes of Minneapolis on this beautiful bike path.",
        snippet: "Best bike ride ever",
        startPointDesc: "Just under the bridge",
        contact: "Jeff Miller",
        phone: "555 123-4567",
        dow: DayOfWeekType.monday,
        latlng: const LatLng(44.9497, -93.3133),
        verified: true,
        verifiedBy: "mQOrVKoRv7NxRuFXFLzJznBIiYl1",
        createdBy: "tDWKQAecW5Msw5yXPQK4h5n7MXR2",
        rideType: RideType.roadRide,
        rideDistance: 20,
      ),
      Ride(
        id: "8",
        title: "Austin Hike and Bike Trail",
        startTime: DateTime.parse("2024-03-15 14:44:00.000"),
        desc:
            "Cycle along the scenic Lady Bird Lake in downtown Austin, Texas.",
        snippet: "Best bike ride ever",
        startPointDesc: "Just under the bridge",
        contact: "Jeff Miller",
        phone: "555 123-4567",
        dow: DayOfWeekType.friday,
        latlng: const LatLng(30.2649, -97.7479),
        verified: false,
        verifiedBy: "",
        createdBy: "tDWKQAecW5Msw5yXPQK4h5n7MXR2",
        rideType: RideType.gravelRide,
        rideDistance: 20,
      ),
      Ride(
        id: "9",
        title: "Seattle Burke-Gilman Trail",
        startTime: DateTime.parse("2024-03-15 14:44:00.000"),
        desc:
            "Ride through parks, neighborhoods, and along scenic waterways on this popular Seattle trail.",
        snippet: "Best bike ride ever",
        startPointDesc: "Just under the bridge",
        contact: "Jeff Miller",
        phone: "555 123-4567",
        dow: DayOfWeekType.monday,
        latlng: const LatLng(47.6607, -122.2886),
        verified: true,
        verifiedBy: "mQOrVKoRv7NxRuFXFLzJznBIiYl1",
        createdBy: "tDWKQAecW5Msw5yXPQK4h5n7MXR2",
        rideType: RideType.gravelRide,
        rideDistance: 20,
      ),
      Ride(
        id: "10",
        title: "Denver Cherry Creek Trail",
        startTime: DateTime.parse("2024-03-15 14:44:00.000"),
        desc:
            "Cycle along the Cherry Creek and enjoy the beautiful scenery of Denver.",
        snippet: "Best bike ride ever",
        startPointDesc: "Just under the bridge",
        contact: "Jeff Miller",
        phone: "555 123-4567",
        dow: DayOfWeekType.tuesday,
        latlng: const LatLng(39.7392, -104.9903),
        verified: true,
        verifiedBy: "mQOrVKoRv7NxRuFXFLzJznBIiYl1",
        createdBy: "tDWKQAecW5Msw5yXPQK4h5n7MXR2",
        rideType: RideType.gravelRide,
        rideDistance: 20,
      ),
      Ride(
        id: "11",
        title: "Cenna Cycle",
        startTime: DateTime.parse("2024-03-15 14:44:00.000"),
        desc:
            "Gravel Ride, Leaves from the shop. This is a friendly ride with an occasional few spicy spots.",
        snippet: "Best bike ride ever",
        startPointDesc: "Start at the shop",
        contact: "Cenna Da Man!",
        phone: "555 123-4567",
        dow: DayOfWeekType.wednesday,
        latlng: const LatLng(40.135667689123494, -105.10335022137203),
        verified: true,
        verifiedBy: "mQOrVKoRv7NxRuFXFLzJznBIiYl1",
        createdBy: "tDWKQAecW5Msw5yXPQK4h5n7MXR2",
        rideType: RideType.gravelRide,
        rideDistance: 20,
      ),
      Ride(
        id: "12",
        title: "Gravel Donkey Ride",
        startTime: DateTime.parse("2024-03-15 14:44:00.000"),
        desc:
            "Leaves every Thursday evening from the Eagle parking lot at 5:00pm",
        snippet: "Best bike ride ever",
        startPointDesc: "Just under the bridge",
        contact: "Jeff Miller",
        phone: "555 123-4567",
        dow: DayOfWeekType.thursday,
        latlng: const LatLng(40.0805057836106, -105.23549907690392),
        verified: true,
        verifiedBy: "mQOrVKoRv7NxRuFXFLzJznBIiYl1",
        createdBy: "tDWKQAecW5Msw5yXPQK4h5n7MXR2",
        rideType: RideType.gravelRide,
        rideDistance: 20,
      ),
      Ride(
        id: "13",
        title: "Full Cycle",
        startTime: DateTime.parse("2024-03-15 14:44:00.000"),
        desc:
            "Road Rides leaving Tuesday and Thursday evening from the shop at 5:30pm",
        snippet: "Best bike ride ever",
        startPointDesc: "Just under the bridge",
        contact: "Jeff Miller",
        phone: "555 123-4567",
        dow: DayOfWeekType.monday,
        latlng: const LatLng(40.017555, -105.258336),
        verified: false,
        verifiedBy: "",
        createdBy: "tDWKQAecW5Msw5yXPQK4h5n7MXR2",
        rideType: RideType.gravelRide,
        rideDistance: 20,
      ),
      Ride(
        id: "14",
        title: "Tony's Awesome Ride",
        startTime: DateTime.parse("2024-03-15 14:44:00.000"),
        desc: "This ride leaves from my house whenever the FUCK I want!",
        snippet: "Best bike ride ever",
        startPointDesc: "Just under the bridge",
        contact: "Ranger Adams",
        phone: "616 956-5434",
        dow: DayOfWeekType.sunday,
        latlng: const LatLng(42.405876, -85.277250),
        verified: true,
        verifiedBy: "mQOrVKoRv7NxRuFXFLzJznBIiYl1",
        createdBy: "tDWKQAecW5Msw5yXPQK4h5n7MXR2",
        rideType: RideType.gravelRide,
        rideDistance: 20,
      ),
      Ride(
        id: "15",
        title: "Tucson Shootout",
        startTime: DateTime.parse("2024-03-15 14:44:00.000"),
        desc: "Probably the most famous ride in the country.",
        snippet: "Best bike ride ever",
        startPointDesc: "Just under the bridge",
        contact: "Jeff Miller",
        phone: "555 123-4567",
        dow: DayOfWeekType.saturday,
        latlng: const LatLng(32.231719, -110.959289),
        verified: false,
        verifiedBy: "",
        createdBy: "tDWKQAecW5Msw5yXPQK4h5n7MXR2",
        rideType: RideType.roadRide,
        rideDistance: 20,
      ),
    ];
  }

  static Future<void> seedSampleRides(Function(List<Ride>) addRidesCallback) async {
    final sampleRides = getSampleRides();
    await addRidesCallback(sampleRides);
  }
}