// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhJneu2nXylQUTI5UXffFG9kVaSBFJanM',
    appId: '1:529913905250:web:587e0903761f725684d13b',
    messagingSenderId: '529913905250',
    projectId: 'mytestmap-f1224',
    authDomain: 'mytestmap-f1224.firebaseapp.com',
    storageBucket: 'mytestmap-f1224.appspot.com',
    measurementId: 'G-R7GHXX5YSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0ipb_hQc_F2o83lYn4_-CAkNhXDfOtMk',
    appId: '1:529913905250:android:7a61a39288e2a31884d13b',
    messagingSenderId: '529913905250',
    projectId: 'mytestmap-f1224',
    storageBucket: 'mytestmap-f1224.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVXCYSjI4v1Q_wW9O-4QdWbT2t6tPEht0',
    appId: '1:529913905250:ios:e6acacecc652f80c84d13b',
    messagingSenderId: '529913905250',
    projectId: 'mytestmap-f1224',
    storageBucket: 'mytestmap-f1224.appspot.com',
    androidClientId:
        '529913905250-e05qjfc27t689sh0d3sbt09dqcqnil6h.apps.googleusercontent.com',
    iosClientId:
        '529913905250-mul095eg0bq657e1d82hgp3j50ue9htd.apps.googleusercontent.com',
    iosBundleId: 'com.ranger.mymap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVXCYSjI4v1Q_wW9O-4QdWbT2t6tPEht0',
    appId: '1:529913905250:ios:2c9220e2db1499ac84d13b',
    messagingSenderId: '529913905250',
    projectId: 'mytestmap-f1224',
    storageBucket: 'mytestmap-f1224.appspot.com',
    androidClientId:
        '529913905250-e05qjfc27t689sh0d3sbt09dqcqnil6h.apps.googleusercontent.com',
    iosClientId:
        '529913905250-igvi0r5rjojfqhtrdv3jb08il3sdno6v.apps.googleusercontent.com',
    iosBundleId: 'com.example.mymap.RunnerTests',
  );
}
